apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kotori-minami
  namespace: server
spec:
  rules:
  - host: kotori-minami.server.10.44.17.151.xip.io
    http:
      paths:
      - backend:
          serviceName: ingress-46a9c614a10def7d13aae679f31f8dc1
          servicePort: 3000
status:
  loadBalancer:
    ingress:
    - ip: 10.44.17.151
